### ISSUE TITLE
Doesn't seem to compile

### ISSUE THREAD

**Issue by benkasminbullock** [paulfloyd/freebsd_valgrind#1]
It doesn't seem to compile on my system:
<pre>
In file included from m_syswrap/syswrap-freebsd.c:59:
m_syswrap/syswrap-freebsd.c:4050:10: error: '__NR_stat' undeclared here (not in a function)
 4050 |    BSDXY(__NR_stat,   sys_stat),   // 188
      |          ^~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4050:4: note: in expansion of macro 'BSDXY'
 4050 |    BSDXY(__NR_stat,   sys_stat),   // 188
      |    ^~~~~
m_syswrap/syswrap-freebsd.c:4050:10: error: array index in initializer not of integer type
 4050 |    BSDXY(__NR_stat,   sys_stat),   // 188
      |          ^~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4050:4: note: in expansion of macro 'BSDXY'
 4050 |    BSDXY(__NR_stat,   sys_stat),   // 188
      |    ^~~~~
m_syswrap/syswrap-freebsd.c:4050:10: note: (near initialization for 'vgModuleLocal_syscall_table')
 4050 |    BSDXY(__NR_stat,   sys_stat),   // 188
      |          ^~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4050:4: note: in expansion of macro 'BSDXY'
 4050 |    BSDXY(__NR_stat,   sys_stat),   // 188
      |    ^~~~~
m_syswrap/syswrap-freebsd.c:4052:10: error: '__NR_lstat' undeclared here (not in a function)
 4052 |    BSDXY(__NR_lstat,   sys_lstat),   // 190
      |          ^~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4052:4: note: in expansion of macro 'BSDXY'
 4052 |    BSDXY(__NR_lstat,   sys_lstat),   // 190
      |    ^~~~~
m_syswrap/syswrap-freebsd.c:4052:10: error: array index in initializer not of integer type
 4052 |    BSDXY(__NR_lstat,   sys_lstat),   // 190
      |          ^~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4052:4: note: in expansion of macro 'BSDXY'
 4052 |    BSDXY(__NR_lstat,   sys_lstat),   // 190
      |    ^~~~~
m_syswrap/syswrap-freebsd.c:4052:10: note: (near initialization for 'vgModuleLocal_syscall_table')
 4052 |    BSDXY(__NR_lstat,   sys_lstat),   // 190
      |          ^~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4052:4: note: in expansion of macro 'BSDXY'
 4052 |    BSDXY(__NR_lstat,   sys_lstat),   // 190
      |    ^~~~~
m_syswrap/syswrap-freebsd.c:4316:11: error: '__NR_statfs6' undeclared here (not in a function); did you mean 'vki_statfs6'?
 4316 |     BSDXY(__NR_statfs6,   sys_statfs6),   // 396
      |           ^~~~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4316:5: note: in expansion of macro 'BSDXY'
 4316 |     BSDXY(__NR_statfs6,   sys_statfs6),   // 396
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4316:11: error: array index in initializer not of integer type
 4316 |     BSDXY(__NR_statfs6,   sys_statfs6),   // 396
      |           ^~~~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4316:5: note: in expansion of macro 'BSDXY'
 4316 |     BSDXY(__NR_statfs6,   sys_statfs6),   // 396
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4316:11: note: (near initialization for 'vgModuleLocal_syscall_table')
 4316 |     BSDXY(__NR_statfs6,   sys_statfs6),   // 396
      |           ^~~~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4316:5: note: in expansion of macro 'BSDXY'
 4316 |     BSDXY(__NR_statfs6,   sys_statfs6),   // 396
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4317:11: error: '__NR_fstatfs6' undeclared here (not in a function); did you mean 'vki_statfs6'?
 4317 |     BSDXY(__NR_fstatfs6,   sys_fstatfs6),   // 397
      |           ^~~~~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4317:5: note: in expansion of macro 'BSDXY'
 4317 |     BSDXY(__NR_fstatfs6,   sys_fstatfs6),   // 397
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4317:11: error: array index in initializer not of integer type
 4317 |     BSDXY(__NR_fstatfs6,   sys_fstatfs6),   // 397
      |           ^~~~~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4317:5: note: in expansion of macro 'BSDXY'
 4317 |     BSDXY(__NR_fstatfs6,   sys_fstatfs6),   // 397
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4317:11: note: (near initialization for 'vgModuleLocal_syscall_table')
 4317 |     BSDXY(__NR_fstatfs6,   sys_fstatfs6),   // 397
      |           ^~~~~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4317:5: note: in expansion of macro 'BSDXY'
 4317 |     BSDXY(__NR_fstatfs6,   sys_fstatfs6),   // 397
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4318:11: error: '__NR_fhstatfs6' undeclared here (not in a function)
 4318 |     BSDXY(__NR_fhstatfs6,  sys_fhstatfs6),   // 398
      |           ^~~~~~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4318:5: note: in expansion of macro 'BSDXY'
 4318 |     BSDXY(__NR_fhstatfs6,  sys_fhstatfs6),   // 398
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4318:11: error: array index in initializer not of integer type
 4318 |     BSDXY(__NR_fhstatfs6,  sys_fhstatfs6),   // 398
      |           ^~~~~~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4318:5: note: in expansion of macro 'BSDXY'
 4318 |     BSDXY(__NR_fhstatfs6,  sys_fhstatfs6),   // 398
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4318:11: note: (near initialization for 'vgModuleLocal_syscall_table')
 4318 |     BSDXY(__NR_fhstatfs6,  sys_fhstatfs6),   // 398
      |           ^~~~~~~~~~~~~~
m_syswrap/priv_types_n_macros.h:298:5: note: in definition of macro 'WRAPPER_ENTRY_XY'
  298 |    [sysno] = { vgSysWrap_##auxstr##_##name##_before, \
      |     ^~~~~
m_syswrap/syswrap-freebsd.c:4318:5: note: in expansion of macro 'BSDXY'
 4318 |     BSDXY(__NR_fhstatfs6,  sys_fhstatfs6),   // 398
      |     ^~~~~
*** Error code 1

Stop.
make[3]: stopped in /usr/home/ben/projects/freebsd_valgrind/coregrind
*** Error code 1

Stop.
make[2]: stopped in /usr/home/ben/projects/freebsd_valgrind/coregrind
*** Error code 1

Stop.
make[1]: stopped in /usr/home/ben/projects/freebsd_valgrind
*** Error code 1

Stop.
make: stopped in /usr/home/ben/projects/freebsd_valgrind
</pre>

**Comment by paulfloyd** [comment]
----- Original Message -----
> 
> It doesn't seem to compile on my system: In file included from
> m_syswrap/syswrap-freebsd.c:59:
> m_syswrap/syswrap-freebsd.c:4050:10: error: '__NR_stat' undeclared
> here (not in a function)
>  4050 |    BSDXY(__NR_stat,   sys_stat),   // 188
>       |          ^~~~~~~~~


Is this with FreeBSD 11?

I'll take a look this evening.

A+
Paul

**Comment by paulfloyd** [comment]
My latest push should at least fix building on FreeBSD 11.

I will try to set up VMs with FreeBSD 11 10 and even 9 to test more thoroughly.

**Comment by benkasminbullock** [comment]
On Tue, 17 Mar 2020 at 20:56, Paul Floyd <notifications@github.com> wrote:

>
>
> ----- Original Message -----
> >
> > It doesn't seem to compile on my system: In file included from
> > m_syswrap/syswrap-freebsd.c:59:
> > m_syswrap/syswrap-freebsd.c:4050:10: error: '__NR_stat' undeclared
> > here (not in a function)
> > 4050 | BSDXY(__NR_stat, sys_stat), // 188
> > | ^~~~~~~~~
>
>
> Is this with FreeBSD 11?
>

Yes, my system is as follows:

[ben@mikan] {06:47 09} ~ 501 $ uname -a
FreeBSD mikan 11.3-RELEASE-p6 FreeBSD 11.3-RELEASE-p6 #0: Tue Jan 28
09:37:40 UTC 2020
root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
 i386
[ben@mikan] {06:47 15} ~ 502 $


> I'll take a look this evening.
>

Thank you. I also have a 64 bit one but I haven't tried it there yet.

[ben@orange] {06:48 21} ~ 501 $ uname -a
FreeBSD orange 11.3-RELEASE-p6 FreeBSD 11.3-RELEASE-p6 #0: Tue Jan 28
09:55:39 UTC 2020
root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
 amd64
[ben@orange] {06:48 23} ~ 502 $

**Comment by paulfloyd** [comment]
> On 17 Mar 2020, at 22:49, Ben Bullock <notifications@github.com> wrote:
> 
> 
> On Tue, 17 Mar 2020 at 20:56, Paul Floyd <notifications@github.com> wrote:
> 
> >
> >
> > ----- Original Message -----
> > >
> > > It doesn't seem to compile on my system: In file included from
> > > m_syswrap/syswrap-freebsd.c:59:
> > > m_syswrap/syswrap-freebsd.c:4050:10: error: '__NR_stat' undeclared
> > > here (not in a function)
> > > 4050 | BSDXY(__NR_stat, sys_stat), // 188
> > > | ^~~~~~~~~
> >
> >
> > Is this with FreeBSD 11?
> >
> 
> Yes, my system is as follows:
> 
> [ben@mikan] {06:47 09} ~ 501 $ uname -a
> FreeBSD mikan 11.3-RELEASE-p6 FreeBSD 11.3-RELEASE-p6 #0: Tue Jan 28
> 09:37:40 UTC 2020
> root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
> i386
> [ben@mikan] {06:47 15} ~ 502 $
> 
> 
> > I'll take a look this evening.
> >
> 
> Thank you. I also have a 64 bit one but I haven't tried it there yet.

I expect the code will compile but not work on x86.

Amd64 should be better.

**Comment by benkasminbullock** [comment]
I didn't have autoconf or automake or libtools installed on the amd64 computer, so I had to install those. I did "autoreconf -i" to build configure then ran that and then ran "make". The same problem as before occured with the supp file, I had to press C-D to make the initial file. 
<pre>
[ben@orange] {15:36 51} freebsd_valgrind 512 $ make
echo "# This is a generated file, composed of the following suppression rules:" > default.supp
echo "# " exp-sgcheck.supp xfree-3.supp xfree-4.supp freebsd.supp >> default.supp
cat  >> default.supp
</pre>
It just hangs there until I press Control-D.

Then the build got this far:
<pre>
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 697: Missing dependency operator
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 708: Need an operator
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 713: Missing dependency operator
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 720: Need an operator
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 722: warning: duplicate script for target "dist-hook" ignored
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 719: warning: using previous script for "dist-hook" defined here
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 723: warning: duplicate script for target "dist-hook" ignored
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 719: warning: using previous script for "dist-hook" defined here
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 724: warning: duplicate script for target "dist-hook" ignored
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 719: warning: using previous script for "dist-hook" defined here
make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 725: Need an operator
make[2]: Fatal errors encountered -- cannot continue
make[2]: stopped in /usr/home/ben/p/freebsd_valgrind/docs
*** Error code 1

Stop.
make[1]: stopped in /usr/home/ben/p/freebsd_valgrind
*** Error code 1

Stop.
make: stopped in /usr/home/ben/p/freebsd_valgrind
</pre>
This is using the latest version of the code.

**Comment by paulfloyd** [comment]
> On 18 Mar 2020, at 07:38, Ben Bullock <notifications@github.com> wrote:
> 
> 
> I didn't have autoconf or automake or libtools installed on the amd64 computer, so I had to install those. The same problem as before occured with the supp file, I had to press C-D to make the initial file.
> 
> [ben@orange] {15:36 51} freebsd_valgrind 512 $ make
> echo "# This is a generated file, composed of the following suppression rules:" > default.supp
> echo "# " exp-sgcheck.supp xfree-3.supp xfree-4.supp freebsd.supp >> default.supp
> cat  >> default.supp
> It just hangs there until I press Control-D.
> 
> Then the build got this far:
> 
> make[2]: "/usr/home/ben/p/freebsd_valgrind/docs/Makefile" line 697: Missing dependency operator

You need to install GNU make as well. I will update the documentation on this.

**Comment by benkasminbullock** [comment]
On Wed, 18 Mar 2020 at 16:15, Paul Floyd <notifications@github.com> wrote:

>
> You need to install GNU make as well. I will update the documentation on
> this.
>

  OK thanks, I have built it with gmake on the amd64. It seemed to compile
OK.

**Comment by paulfloyd** [comment]
OK, good. Don't hesitate to open new issues if you encounter problems.
