### ISSUE TITLE
Assertion failed: (res != -1), function main, file scalar.c, line 225 [x86]

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#106]
Running without valgrind (so as to check failing test) on "FreeBSD 12.1-RELEASE-p6 GENERIC  i386" --
```
$ ./scalar <scalar.c
[...]
---------------------------------------------------------
 49:            SYS_getlogin 0s 0m
---------------------------------------------------------
Assertion failed: (res != -1), function main, file scalar.c, line 225.
Abort trap (core dumped)
```
and indeed, res == -1
```
#4  0x00402ba9 in main () at scalar.c:225
225	   SY(SYS_getlogin); SUCC;
(gdb) print res
$1 = -1
```

**Comment by paulfloyd** [comment]
Whilst I'm more or less expecting this test case to be fairly flaky on different platforms and OS versions, getlogin() isn't a function that I would expect to show differences. I think I see my mistake though. I went by the manpage for "getlogin()" which takes no arguments whilst syscall.master says
```
49	AUE_GETLOGIN	STD {
		int getlogin(
		    _Out_writes_z_(namelen) char *namebuf,
		    u_int namelen
		);
	}
```

**Comment by nbriggs** [comment]
Yes, and also I think you might change the SUCC; to a FAIL; because passing 0 for the address of the buffer (assuming the comment about x0 being 0 though uninitialized is correct) is going to cause it to produce res = -1, errno = EFAULT.

**Comment by paulfloyd** [comment]
Pushed
To https://github.com/paulfloyd/freebsd_valgrind.git
   cbfddc494..fb9e9ca41  freebsd -> freebsd
