### ISSUE TITLE
test scalar expected output needs split for amd64/i386

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#112]
Attached are the stderr.out and stderr.diff from running the most recent scalar test on an i386 system.

[scalar.stderr.diff.txt](https://github.com/paulfloyd/freebsd_valgrind/files/4793960/scalar.stderr.diff.txt)
[scalar.stderr.out.txt](https://github.com/paulfloyd/freebsd_valgrind/files/4793962/scalar.stderr.out.txt)

**Comment by paulfloyd** [comment]
Passes for me with this commit
commit 26f8cc87553b6476d30f6aa198e56417dd437311

**Comment by nbriggs** [comment]
I agree... passes for me too.
