### ISSUE TITLE
Warning: noted but unhandled ioctl 0x2000741c

### ISSUE THREAD

**Issue by paulfloyd** [paulfloyd/freebsd_valgrind#15]
To reproduce

./vg-in-place --tool=none --read-var-info=yes xterm

Looks like this is TIOCPTMASTER

Looking at syswrap-freebsd.c there is

```
/* On FreeBSD, ALL ioctl's are IOR/IOW encoded.  Just use the default decoder */
   if (SimHintiS(SimHint_lax_ioctls, VG_(clo_sim_hints))) {
      /*
      * Be very lax about ioctl handling; the only
      * assumption is that the size is correct. Doesn't
      * require the full buffer to be initialized when
      * writing.  Without this, using some device
      * drivers with a large number of strange ioctl
      * commands becomes very tiresome.
      */
   } else if (/* size == 0 || */ dir == _VKI_IOC_NONE) {
	 static Int moans = 3;
	 if (moans > 0 && !VG_(clo_xml)) {
	    moans--;
	    VG_(message)(Vg_UserMsg, 
			 "Warning: noted but unhandled ioctl 0x%lx"
			 " with no size/direction hints\n",
			 ARG2); 
```

Well this ioctl is 

`#define	TIOCPTMASTER	 _IO('t', 28)		/* pts master validation */
`

So the first comment is not true and dir is NONE so we get the moan message.

**Comment by nbriggs** [comment]
I would have thought that the check should be whether the <code>dir</code> value is one of the possible ones, and that only if the dir is not NONE (FreeBSD's VOID)  then the size hint should be non-zero... except there's this:
```
/usr/include/sys/ioccom.h:#define	_IOWINT(g,n)	_IOC(IOC_VOID,	(g), (n), sizeof(int))
```
which breaks that assumption.
But, dir == NONE and size == 0 probably shouldn't be complained about.

**Comment by paulfloyd** [comment]
The same issue is logged upstream
https://bugs.kde.org/show_bug.cgi?id=170510

**Comment by paulfloyd** [comment]
In the end pushed the change but left the message unaltered.
To https://github.com/paulfloyd/freebsd_valgrind.git
   0cb09eadd..2367a1dd3  freebsd -> freebsd

**Comment by paulfloyd** [comment]
And now changed the message and done for Linux, clused upstream.
