### ISSUE TITLE
Fails to run in an x86 jail

### ISSUE THREAD

**Issue by paulfloyd** [paulfloyd/freebsd_valgrind#20]
Maybe I don't know how to set up a jail correctly but I get

./vg-in-place pwd
ELF interpreter /libexec/ld-elf.so.1 not found, error 8
Abort trap

The jail:
uname -a
FreeBSD eulerx86.home 12.1-RELEASE-p3 FreeBSD 12.1-RELEASE-p3 GENERIC  i386

The host:
uname -a
FreeBSD euler 12.1-RELEASE-p3 FreeBSD 12.1-RELEASE-p3 GENERIC  amd64

**Comment by kevans91** [comment]
I think this must be an artifact of how the jail was constructed; with a fresh i386 sysroot and my lame test files from earlier:

```
# uname -a
FreeBSD  13.0-CURRENT FreeBSD 13.0-CURRENT #0 ad49a04033c-c269301(master): Sun Jun 14 23:27:18 CDT 2020     root@viper.audeuro.com:/usr/obj/pkgbase/usr/src/amd64.amd64/sys/GENERIC  i386
# freebsd-version
12.1-RELEASE
# cc test1.c
# valgrind ./a.out
==94212== Memcheck, a memory error detector
==94212== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==94212== Using Valgrind-3.17.0.GIT and LibVEX; rerun with -h for copyright info
==94212== Command: ./a.out
==94212==
==94212==
==94212== HEAP SUMMARY:
==94212==     in use at exit: 4,096 bytes in 1 blocks
==94212==   total heap usage: 1 allocs, 0 frees, 4,096 bytes allocated
==94212==
==94212== LEAK SUMMARY:
==94212==    definitely lost: 4,096 bytes in 1 blocks
==94212==    indirectly lost: 0 bytes in 0 blocks
==94212==      possibly lost: 0 bytes in 0 blocks
==94212==    still reachable: 0 bytes in 0 blocks
==94212==         suppressed: 0 bytes in 0 blocks
==94212== Rerun with --leak-check=full to see details of leaked memory
==94212==
==94212== For lists of detected and suppressed errors, rerun with: -s
==94212== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

How was the jail constructed and started? In my case, I've downloaded the 12.1/i386 "raw" VM image and mounted its root at /mnt, then `jail -c path=/mnt command=/bin/sh`.

**Comment by paulfloyd** [comment]
I suspected that my setup was bad. This is my only experience with jails so far. In rc.conf I have
```
#jail_enable="YES"
#jail_list="x86jail"
```

and jail.conf contains
```
exec.start = "/bin/sh /etc/rc";
exec.stop = "/bin/sh /etc/rc.shutdown";

x86jail {
path = /usr/jails/x86jail;
mount.devfs;
host.hostname = "eulerx86.home";
ip4.addr = 192.168.1.254;
#interface = vtnet0;
};
```

**Comment by paulfloyd** [comment]
https://docs.freebsd.org/en/books/handbook/jails/
https://gundersen.net/32bit-jail-on-64bit-freebsd/

**Comment by paulfloyd** [comment]
My initial jail setup must have been wrong.

I'm able to build and run Valgrind.

However it doesn't look like a good alternative to VirtualBox. The jail environment has quite a few restrictions

none/tests gives

== 169 tests, 7 stderr failures, 4 stdout failures, 0 stderrB failures, 0 stdoutB failures, 0 post failures ==
none/tests/allexec32                     (stdout)
none/tests/allexec32                     (stderr)
none/tests/allexec64                     (stdout)
none/tests/allexec64                     (stderr)
none/tests/fdleak_ipv4                   (stderr)
none/tests/manythreads                   (stdout)
none/tests/manythreads                   (stderr)
none/tests/mq                            (stderr)
none/tests/nocwd                         (stdout)
none/tests/nocwd                         (stderr)
none/tests/sem                           (stderr)

But it's there if I need it
