### ISSUE TITLE
String function detours

### ISSUE THREAD

**Issue by clausecker** [paulfloyd/freebsd_valgrind#206]
Greetings!

Work on the amd64 SIMD enhancement project has now concluded and is currently undergoing acceptance testing.  You can find the full list of functions that may need to be detoured [in the blog post](https://freebsdfoundation.org/blog/a-sneak-peek-simd-enhanced-string-functions-for-amd64/).

**Comment by paulfloyd** [comment]
Thanks for the heads  up.

memccpy is the only one without a redirect, and that doesn't (yet) do any form of parallelism.

musl does seem to do 4/8 byte processing
https://elixir.bootlin.com/musl/latest/source/src/string/memccpy.c#L17

**Comment by clausecker** [comment]
You can find the code pending acceptance testing in the [acceptance-testing](https://github.com/clausecker/freebsd-src/commits/acceptance-testing) branch of my FreeBSD source fork.
