### ISSUE TITLE
unable to open output files/remove scratch files, no useful error reporting

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#37]
For some seemingly trivial programs, valgrind (on FreeBSD 12.p-RELEASE-p3) using
```
$ valgrind --version
valgrind-3.16.0.GIT
```
will run without error:
```$ valgrind --tool=massif date
==62526== Massif, a heap profiler
==62526== Copyright (C) 2003-2017, and GNU GPL'd, by Nicholas Nethercote
==62526== Using Valgrind-3.16.0.GIT and LibVEX; rerun with -h for copyright info
==62526== Command: date
==62526== 
Tue Apr 14 12:20:43 PDT 2020
==62526== 
$ 
```
but for other also seemingly trivial programs it will reproducibly fail to open output files and delete scratch files (but gives no indication of what error it might have encountered):
```
$ valgrind --tool=massif /bin/echo
==62519== Massif, a heap profiler
==62519== Copyright (C) 2003-2017, and GNU GPL'd, by Nicholas Nethercote
==62519== Using Valgrind-3.16.0.GIT and LibVEX; rerun with -h for copyright info
==62519== Command: /bin/echo
==62519== 

==62519== 
==62519== Error: can not open xtree output file `/usr/home/briggs/massif.out.62519'
==62519== could not unlink /tmp/vgdb-pipe-from-vgdb-to-62519-by-briggs-on-???
==62519== could not unlink /tmp/vgdb-pipe-to-vgdb-from-62519-by-briggs-on-???
==62519== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-62519-by-briggs-on-???
```

**Comment by paulfloyd** [comment]
I've seen the unlink problems in a few of the regression tests:

- none/tests/nocwd
- none/tests/scripts/bug231357

I don't know why the unlink call is failing.

However, I see that nocwd is a C executable that does an exec of 'echo' and bug bug231357 generates a script that calls echo. So clearly 'echo' is the common denominator.

**Comment by nbriggs** [comment]
/bin/jot causes a failure too, so it's not just 'echo'.  I thought initially that the difference was calls to the cap_xxxx capability functions, but I have another failing program that doesn't use any cap_xxxx calls.

**Comment by paulfloyd** [comment]
I see also that this is a regression compared to ports Valgrind.

**Comment by nbriggs** [comment]
Ports valgrind doesn't seem to have built correctly since 2019-08-06 because of the usage of "ELF_NOTE_GNU".  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239669 -- I don't seem to be able to find a version in ports for 12.x that works for i386 architecture.

**Comment by nbriggs** [comment]
OK -- got one cause narrowed down:  If the program in question does a chroot() call to, for example, "/var/empty" then valgrind is unable to do the file i/o it wants to.  Perhaps valgrind ought to be opening any output files up front, before the subject program manages to modify the environment?  I suspect that the issue with <code>echo</code> and <code>jot</code> is the "capabilities" calls they make, while my actual problem is the "chroot()", but it's really just two instances of the same class of problem.

test case:  chroot-test.c
```
#include <unistd.h>

int main(int argc, char *argv[])
{
  if (argc > 1) chroot("/var/empty");
  return(0);
}
```

results:
```
./vg-in-place --tool=massif /tmp/chroot-test
==15247== Massif, a heap profiler
==15247== Copyright (C) 2003-2017, and GNU GPL'd, by Nicholas Nethercote
==15247== Using Valgrind-3.16.0.GIT and LibVEX; rerun with -h for copyright info
==15247== Command: /tmp/chroot-test
==15247== 
==15247== 
# ./vg-in-place --tool=massif /tmp/chroot-test dochroot
==15250== Massif, a heap profiler
==15250== Copyright (C) 2003-2017, and GNU GPL'd, by Nicholas Nethercote
==15250== Using Valgrind-3.16.0.GIT and LibVEX; rerun with -h for copyright info
==15250== Command: /tmp/chroot-test dochroot
==15250== 
==15250== 
==15250== Error: can not open xtree output file `/usr/home/briggs/freebsd_valgrind/massif.out.15250'
==15250== could not unlink /tmp/vgdb-pipe-from-vgdb-to-15250-by-root-on-???
==15250== could not unlink /tmp/vgdb-pipe-to-vgdb-from-15250-by-root-on-???
==15250== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-15250-by-root-on-???
```

**Comment by nbriggs** [comment]
Also note that in massif's ms_main.c there's a comment saying 

> // Setup output filename.  Nb: it's important to do this now, ie. as late                                                                                                                        
   // as possible.  If we do it at start-up and the program forks and the                                                                                                                           
   // output file format string contains a %p (pid) specifier, both the                                                                                                                             
   // parent and child will incorrectly write to the same file;  this                                                                                                                               
   // happened in 3.3.0.

So you run into trouble either way.

**Comment by paulfloyd** [comment]
For the ports regression, I was referring to amd64. I'll try to comment out the capsicum syscalls to see what that changes.

As for how to fix the problem, that looks like it will be difficult. Valgrind only has a single process executing (not counting forks). This means that the host gets affected by guest syscalls. Ideally from the Valgrind perspective we'd like to have either
- a 'split' model with the host running in normal mode and the guest running in capability mode or
- the ability to exit capability mode when the guest terminates

I imagine that doing either of these would compromise the capabilities security model, and so they aren't allowed.

I have one idea for a possible solution, at least for the unlink

```
fork
   parent
      wait for child
      perform cleanup

   child
      execute guest
      record capabilities state
      only cleanup if not in capabilities mode
```

**Comment by nbriggs** [comment]
I must admit I'm a lot less concerned about the unlink() calls -- I can do that clean up after the fact.  But when it fails to write the collected data to its output file there's absolutely nothing that I can do to recover.

**Comment by paulfloyd** [comment]
Yes. This also seems to be an issue on Linux (a quick google seems to show that 'seccomp' is roughly the equivalent of capsicum - I know little about security features like this).

See [here ](https://bugzilla.mozilla.org/show_bug.cgi?id=1288726)for instance.

**Comment by paulfloyd** [comment]
Quick confirmation. Removing 'cap_enter' removes the unlink errors. And puts back the missing syscall message.

**Comment by nbriggs** [comment]
I'm running with your code as of a few minutes ago:

> commit bbf055db6563172fd62dc2fd084059ca6bd4dadb (HEAD -> freebsd, origin/freebsd, origin/HEAD)

and that version currently fails for /bin/echo as it did before:
```
$ valgrind /bin/echo
==28536== Memcheck, a memory error detector
==28536== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==28536== Using Valgrind-3.16.0.GIT and LibVEX; rerun with -h for copyright info
==28536== Command: /bin/echo
==28536== 

[...]
==28536== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==28536== could not unlink /tmp/vgdb-pipe-from-vgdb-to-28536-by-briggs-on-???
==28536== could not unlink /tmp/vgdb-pipe-to-vgdb-from-28536-by-briggs-on-???
==28536== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-28536-by-briggs-on-???
$ 
```
Was that what you expected?
<code>/bin/echo</code> uses the following "cap_..." calls:
```
cap_rights_limit(0,{ CAP_READ,CAP_SEEK_TELL,CAP_FCNTL,CAP_FSTAT,CAP_EVENT,CAP_IOCTL }) = 0 (0x0)
cap_ioctls_limit(0x0,0xffbfec1c,0x3)		 = 0 (0x0)
cap_fcntls_limit(0,CAP_FCNTL_GETFL)		 = 0 (0x0)
cap_rights_limit(1,{ CAP_WRITE,CAP_SEEK_TELL,CAP_FCNTL,CAP_FSTAT,CAP_EVENT,CAP_IOCTL }) = 0 (0x0)
cap_ioctls_limit(0x1,0xffbfec1c,0x3)		 = 0 (0x0)
cap_fcntls_limit(1,CAP_FCNTL_GETFL)		 = 0 (0x0)
cap_rights_limit(2,{ CAP_WRITE,CAP_SEEK_TELL,CAP_FCNTL,CAP_FSTAT,CAP_EVENT,CAP_IOCTL }) = 0 (0x0)
cap_ioctls_limit(0x2,0xffbfec1c,0x3)		 = 0 (0x0)
cap_fcntls_limit(2,CAP_FCNTL_GETFL)		 = 0 (0x0)
cap_enter()					 = 0 (0x0)
```

For the code that I was personally interested in debugging, I commented out the <code>chroot()</code>, and <code>set...uid()</code> calls, and was able to successfully run the massif tool and collect the output.  It doesn't use any of the "cap_..." calls.

I notice that in a probably unrelated change you fixed the missing syscall for FreeBSD 12.x "df".

**Comment by paulfloyd** [comment]
I didn't push the change. I just quickly commented out the 'cap_enter' syscall wrapper and ran one of the tests. As a short term fix, I'll probably just add a variable to indicate capability mode and if that is set, not make the gdb pipe unlink calls.

As for the massif output files, this might just have to be a documented limitation, with the suggestion that the user does something like

```
#include "valgrind.h"

...

if (!RUNNING_ON_VALGRIND) {
   cap_enter(); // etc
} // else do nothing
```

**Comment by nbriggs** [comment]
OK, got it.  Changing the program source will be useful for developers of a particular program who regularly use valgrind... less so for people (who are developers, but not of the program in question) who try to debug an issue on released software but don't want to rebuild -- but that's probably a rare case and could be covered by clearly documenting the limitations.

Did you consider a valgrind runtime option that disables problematic syscall(s)?

In my specific case the problem wasn't a capability issue, it was that the code had done <code>chroot("/var/empty"); chdir("/");</code>, and I hadn't noticed it.

Another thing to consider would be a message when valgrind notices syscalls that are likely to be problematic, for example something like,
> ==<pid>== Note: use of capabilities detected, see documented limitations.

**Comment by paulfloyd** [comment]
I think that both would be good, and to include the name of the option in the warning.

**Comment by paulfloyd** [comment]
I'll leave the possibility for disabling cap_enter() for now. It could be abused.

I now print a warning

WARNING: Valgrind may not operate correctly in capability mode.
         Please consider disabling capability by using the RUNNING_ON_VALGRIND mechanism.
         See http://valgrind.org/docs/manual/manual-core-adv.html#manual-core-adv.clientreq

Also don't try to unlink the gdbserver pipes.

All in push
   1fed23440..7dfb8bc6d  freebsd -> freebsd
