### ISSUE TITLE
"No rule to make target 'exp-sgcheck.supp' ..."

### ISSUE THREAD

**Issue by benkasminbullock** [paulfloyd/freebsd_valgrind#42]
On commit 2f2f1fb40a0d9bcc26c7f26ccad17f13ac87d573, I am getting the following:
`````
$ ./configure --prefix=/home/ben/software/install
...
$ gmake
gmake: *** No rule to make target 'exp-sgcheck.supp', needed by 'default.supp'.  Stop.
`````

**Comment by paulfloyd** [comment]
Upstream Valgrind is getting ready for version 3.16.  As part of this, exp-sgcheck [has been removed.](https://github.com/paulfloyd/freebsd_valgrind/commit/40187fcd61ee877f78701c46a74ac1dadbe65b3d)

You should do the following

1. gmake distclean
2. ./autogen.sh
3. ./configure {options}
4. gmake
