### ISSUE TITLE
improve clang compatibility: use -Wl,-u,_start vs -u _start for FreeBSD common ld flags

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#54]
gcc accepts as equivalent <code>-u _start</code> and <code>-Wl,-u,_start</code> but clang warns about unused command line arguments in the <code>-u</code> case.
Thus we can modify the Makefile.tool.am in the FreeBSD case, where clang is the default C compiler, to reduce the number of warnings while still retaining compatibility if gcc has been installed:

```
diff --git a/Makefile.tool.am b/Makefile.tool.am
index b0b7160df..9671f0ffe 100644
--- a/Makefile.tool.am
+++ b/Makefile.tool.am
@@ -40,7 +40,7 @@ TOOL_LDFLAGS_COMMON_SOLARIS = \
        -static -nodefaultlibs -nostartfiles -u _start \
        -Wl,-M,/usr/lib/ld/map.noexstk
 TOOL_LDFLAGS_COMMON_FREEBSD = -static \
-       -nodefaultlibs -nostartfiles -u _start @FLAG_NO_BUILD_ID@
+       -nodefaultlibs -nostartfiles -Wl,-u,_start @FLAG_NO_BUILD_ID@
 
 TOOL_LDFLAGS_X86_LINUX = \
        $(TOOL_LDFLAGS_COMMON_LINUX) @FLAG_M32@
```

**Comment by paulfloyd** [comment]
GCC compatibility is important if ever this gets accepted upstream.

**Comment by nbriggs** [comment]
I agree.  I'm not suggesting any incompatible changes.

**Comment by paulfloyd** [comment]
Patch pushed with
To https://github.com/paulfloyd/freebsd_valgrind.git
   4f59c7567..93607aa97  freebsd -> freebsd
