### ISSUE TITLE
regtest reports missing/extra files in memcheck/tests/freebsd/Makefile.am

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#55]
regtest reports

>...checking makefile consistency
memcheck/tests/freebsd/Makefile.am:1: error: statvfs.stderr.exp is missing in EXTRA_DIST
memcheck/tests/freebsd/Makefile.am:1: error: statvfs.stderr is in EXTRA_DIST but doesn't exist

Which suggests the entry in memcheck/tests/freebsd/Makefile.am for EXTRA_DIST files should probably be for <code>statvfs.stderr.exp</code> rather than <code>statvfs.stderr</code>

**Comment by paulfloyd** [comment]
Yes it should be. I saw just after pushing the change, but I've already modified the file, so I'll probably wait until the next few tests are ready to push.

**Comment by paulfloyd** [comment]
Pushed a fix earlier.
