### ISSUE TITLE
memcheck/tests/amd64-freebsd tests need prereq to stop them attempting to run on x86 arch

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#65]
The test framework, running on a FreeBSD x86 system attempts to execute the posix_fadvise and posix_fallocate tests from the memcheck/tests/amd64-freebsd/ directory.  Presumably either the test framework shouldn't be going in here, or the .vgtest files should have a prerequisite defined for ../tests/arch_test amd64 (and ../tests/os_test freebsd ?)

**Comment by paulfloyd** [comment]
I just pushed a change that should fix this. 'tests/platform_test' didn't have anything freebsd-specific.
