### ISSUE TITLE
/lib/libc.so.7 posix_fadvise and posix_fallocate use conditional jump/move [clang]

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#68]
The expected output for memcheck tests posix_fadvise and posix_fallocate, at least on x86-freebsd using default (clang) compiler, need to be updated as the libc (currently /lib/libc.so.7) uses conditional jump or move that depends on the (uninitialized in the test) argument.

Diff files attached (as .txt since Github objects to plain .diff)

[posix_fadvise.stderr.diff.txt](https://github.com/paulfloyd/freebsd_valgrind/files/4566415/posix_fadvise.stderr.diff.txt)
[posix_fallocate.stderr.diff.txt](https://github.com/paulfloyd/freebsd_valgrind/files/4566416/posix_fallocate.stderr.diff.txt)

**Comment by paulfloyd** [comment]
Added to global suppression file in push
To https://github.com/paulfloyd/freebsd_valgrind.git
   7db733f0b..82502057a  freebsd -> freebsd
