### ISSUE TITLE
couple of missing entries in EXTRA_DIST for new test supponlyobj

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#69]
memcheck/tests/freebsd/Makefile.am:1: error: supponlyobj.stderr.exp is missing in EXTRA_DIST
memcheck/tests/freebsd/Makefile.am:1: error: supponlyobj.vgtest is missing in EXTRA_DIST

**Comment by paulfloyd** [comment]
Pushed
To https://github.com/paulfloyd/freebsd_valgrind.git
   4bb30cbbb..ff3182b29  freebsd -> freebsd
