### ISSUE TITLE
memcheck/tests/origin4-many fails because of compiler optimization [clang]

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#74]
clang (version 9) with optimization above 1 optimizes the origin4-many main program down to:
```
Dump of assembler code for function main:
   0x004012c0 <+0>:	push   %ebp
   0x004012c1 <+1>:	mov    %esp,%ebp
   0x004012c3 <+3>:	addl   $0xd4,0x40302c
   0x004012cd <+13>:	xor    %eax,%eax
   0x004012cf <+15>:	pop    %ebp
   0x004012d0 <+16>:	ret    
End of assembler dump.
```
so none of the <code>malloc(...)</code> calls get made.  This is another case where slapping a <code>volatile</code> on the <code>int*</code> declarations will prevent the optimization, alternatively the test could be compiled with -O0 (or -O1)

**Comment by paulfloyd** [comment]
Made the variables volatile
To https://github.com/paulfloyd/freebsd_valgrind.git
   8bedb8d1d..01ba13a76  freebsd -> freebsd
