### ISSUE TITLE
fix generated insn_xxx.c to be compatible with clang for inline asm [clang]

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#80]
When compiling the generated insn_sse.c with clang, it dies with
```
insn_sse.c:85:10: error: inline assembly requires more registers than available
         "fxsave %6\n"
         ^
```
This could be a problem with clang, but it can be avoided by making the <code>state</code> variable a global instead of stack allocated.
With this change, the conditional exclusion of insn_sse and insn_sse2 based on using clang can be removed.

[patch-gen-insn.txt](https://github.com/paulfloyd/freebsd_valgrind/files/4602623/patch-gen-insn.txt)

**Comment by paulfloyd** [comment]
Patch applied with push
To https://github.com/paulfloyd/freebsd_valgrind.git
   c832a3675..de86498bc  freebsd -> freebsd

**Comment by nbriggs** [comment]
You just reverted the change for this.  It's back to failing.

**Comment by paulfloyd** [comment]
----- Original Message -----
> You just reverted the change for this. It's back to failing.

I was a bit overzealous in trying to removes diffs wrt upstream sourceware. I've reverted the revert.
