### ISSUE TITLE
warning: macro expansion producing 'defined' has undefined behavior [clang]

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#96]
Clang (since about 2016) warns for macros that produce undefined behavior --
```
m_debuginfo/tinfl.c:182:45: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if MINIZ_USE_UNALIGNED_LOADS_AND_STORES && MINIZ_LITTLE_ENDIAN
                                            ^

m_debuginfo/tinfl.c:54:37: note: expanded from macro 'MINIZ_LITTLE_ENDIAN'
#define MINIZ_LITTLE_ENDIAN       ( defined(VG_LITTLEENDIAN) )
                                    ^
1 warning generated.
```

**Comment by paulfloyd** [comment]
I had seen this. Building with -Weverything thows up a lot of GCCisms.

I'm not sure of removing these warnings will be acceptable upstream. So the 'solution' might be to add -Wno-expansion-to-defined to CFLAGS.

**Comment by paulfloyd** [comment]
Added -Wno-expansion-to-defined (only clang and FreeBSD)
To https://github.com/paulfloyd/freebsd_valgrind.git
   39c9c1ec8..3a0ed5c26  freebsd -> freebsd
