### ISSUE TITLE
missing file memcheck/tests/freebsd/filter_scalar

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#98]
Commit 7c8bbcb67a introduced a reference to filter_scalar in memcheck/tests/freebsd/Makefile.am, but didn't include the file itself, so a clean build fails with
```
Making all in freebsd
gmake[4]: Entering directory '/usr/home/briggs/freebsd_valgrind/memcheck/tests/freebsd'
gmake[4]: *** No rule to make target 'filter_scalar', needed by 'all-am'.  Stop.
```
etc.   Oops.

**Comment by nbriggs** [comment]
As you can probably guess... I'm doing clean builds testing my fix to configure.ac for Issue #95

**Comment by paulfloyd** [comment]
Fixed
To https://github.com/paulfloyd/freebsd_valgrind.git
   0a489c8cd..d4c752b68  freebsd -> freebsd
